# Generated by Django 3.2.4 on 2021-06-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailgSent',
        ),
    ]
