# Generated by Django 3.2.4 on 2021-06-24 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0002_delete_emailgsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailgSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_csv', models.FileField(null=True, upload_to='media/csv')),
                ('reciever_csv', models.FileField(null=True, upload_to='media/csv')),
                ('sent', models.BooleanField(default=False, null=True)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=1000)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
