# Generated by Django 3.2.4 on 2021-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_emailsent_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsent',
            name='reciever_csv',
        ),
        migrations.RemoveField(
            model_name='emailsent',
            name='sender_csv',
        ),
        migrations.AddField(
            model_name='emailsent',
            name='reciever_email',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='emailsent',
            name='sender_email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
