# Generated by Django 3.2.4 on 2021-06-26 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0006_auto_20210626_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='del_status',
            field=models.BooleanField(default=False),
        ),
    ]
