# Generated by Django 3.2.4 on 2021-06-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0007_emailsent_del_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='destroyed_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
