# Generated by Django 3.2.4 on 2021-06-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0008_emailsent_destroyed_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailsent',
            name='destroyed_on',
        ),
    ]
