# Generated by Django 3.2.4 on 2021-06-27 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailer', '0009_remove_emailsent_destroyed_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailsent',
            old_name='del_status',
            new_name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='emailsent',
            name='sent',
        ),
        migrations.AlterField(
            model_name='emailsent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
