# Generated by Django 3.2.4 on 2021-06-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0010_auto_20210627_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='cache_checker',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
