# Generated by Django 3.2.4 on 2021-06-27 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0011_emailsent_cache_checker'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailSentInti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailer.emailsent')),
            ],
        ),
    ]
