# Generated by Django 3.2.4 on 2021-06-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0013_emailsentinti_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsent',
            name='delivery_status_read',
            field=models.BooleanField(default=False),
        ),
    ]
