# Generated by Django 3.2.4 on 2021-07-01 11:25

from django.db import migrations, models
import mailer.models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0016_rename_cover_image_emailfile_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailfile',
            name='attachment',
        ),
        migrations.AddField(
            model_name='emailfile',
            name='reciever_attachment',
            field=models.FileField(null=True, upload_to=mailer.models.file_for_email),
        ),
        migrations.AddField(
            model_name='emailfile',
            name='sender_attachment',
            field=models.FileField(null=True, upload_to=mailer.models.file_for_email),
        ),
    ]
