# Generated by Django 3.2.4 on 2021-07-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0017_auto_20210701_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsentinti',
            name='email_init',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mailer.emailsent'),
        ),
    ]
