# Generated by Django 3.2.4 on 2021-06-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('destroy_on', models.DateTimeField(null=True)),
                ('payment_history_init', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.paymenthistory')),
            ],
        ),
    ]
