# Generated by Django 3.2.4 on 2021-06-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_activeaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activeaccount',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='activeaccount',
            name='destroy_on',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='destroy_on',
            field=models.DateTimeField(null=True),
        ),
    ]
