# Generated by Django 3.2.4 on 2021-06-26 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20210626_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='destroy_on',
        ),
    ]
