# Generated by Django 3.2.4 on 2021-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_auto_20210626_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='subscriptionoption',
            name='cost',
            field=models.FloatField(),
        ),
    ]
