# Generated by Django 3.2.4 on 2021-06-28 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_auto_20210626_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='sub_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.subscriptionoption'),
        ),
    ]
