# Generated by Django 3.2.4 on 2021-06-29 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_subscriptionoption_stripe_price_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionoption',
            old_name='stripe_price_id',
            new_name='stripe_price_code',
        ),
    ]
