# Generated by Django 3.2.4 on 2021-06-29 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_rename_stripe_price_id_subscriptionoption_stripe_price_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoption',
            name='stripe_price_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
