# Generated by Django 3.2.4 on 2021-06-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_auto_20210629_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionoption',
            name='paypal_price_code',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
