# Generated by Django 3.2.4 on 2021-06-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_subscriptionoption_paypal_price_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='paymen_state',
            new_name='paymen_completed',
        ),
    ]
