# Generated by Django 3.2.4 on 2021-07-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_alter_subscriptionoption_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='email_amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_receipt',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='receipt_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
