# Generated by Django 3.2.4 on 2021-07-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_auto_20210701_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='email_amount',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='receipt_status',
            field=models.CharField(default='Incomplete', max_length=10, null=True),
        ),
    ]
