# Generated by Django 3.2.4 on 2021-07-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_subscriptionoption_email_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='cost',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionoption',
            name='cost',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
