# Generated by Django 3.2.4 on 2021-07-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_auto_20210701_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_reciept',
            new_name='customer_payment_reciept',
        ),
    ]
