# Generated by Django 3.2.4 on 2021-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_rename_payment_reciept_paymenthistory_customer_payment_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='payment_receipt',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='payment_reciept',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
