# Generated by Django 3.2.4 on 2021-07-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_auto_20210701_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenthistory',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='name',
        ),
    ]
