# Generated by Django 3.2.4 on 2021-07-02 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20210702_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='paymen_completed',
            new_name='payment_completed',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_desc',
            new_name='payment_platform_desc',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_platform',
            new_name='payment_platform_name',
        ),
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='payment_reciept',
            new_name='payment_platform_reciept',
        ),
    ]
