# Generated by Django 3.2.4 on 2021-07-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_auto_20210702_0759'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='last_email_amount',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
