# Generated by Django 3.2.4 on 2021-07-06 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0024_paymenthistory_last_email_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='un_sub_hint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extended_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorized_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
