# Generated by Django 3.2.4 on 2021-06-26 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_otp_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='two_step_verification',
            new_name='subscribed',
        ),
    ]
