# Generated by Django 3.2.4 on 2021-06-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_two_step_verification_profile_subscribed'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_sub',
            field=models.DateTimeField(null=True),
        ),
    ]
