# Generated by Django 3.2.4 on 2021-07-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_profile_last_payment_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_amount',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
