# Generated by Django 3.2.4 on 2021-07-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_email_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_sent',
            field=models.PositiveSmallIntegerField(default=0, null=True),
        ),
    ]
